In [4]:
import numpy as np

## Creating array from list

In [4]:
arr_id = np.array([1,2,3,4,5,6,7])
print("1D array: ",arr_id)

arr_2d = np.array([[1,2,3,4,5],[2,4,6,4,3]])
print("2D array: ",arr_2d)

1D array:  [1 2 3 4 5 6 7]
2D array:  [[1 2 3 4 5]
 [2 4 6 4 3]]


# List vs numpy array

In [ ]:
py_list = [1,2,3,4]
print("Multiplication: ",py_list*2)
# Here the list gets concatenated when we try to multiply

np_arr = np.array([1,2,3,4])
print("Multiplication: ",np_arr*2)
# Element wise multiplication

Multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Multiplication:  [2 4 6 8]


# Creating an array from scratch

In [ ]:
# Array of zeroes
zeroes = np.zeros((3,4))
print("Zeroes: \n",zeroes)


# Array of ones
ones = np.ones((3,4))
print("Zeroes: \n",ones)

# Array of constant values
full = np.full((2, 2), 7)
print("full array: \n", full)

# generates random values from 0 to 1
random = np.random.random((2, 3))
print("random array: \n", random)

# generates a sequence of numbers
sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)

Zeroes: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Zeroes: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.6166971  0.26126325 0.4198518 ]
 [0.32195149 0.82672117 0.13043674]]
sequnce array: 
 [ 0  2  4  6  8 10]


# Vector, Matrix and Tensor

In [6]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

# 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix: ", matrix)

# 3D array
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\nTensor: ", tensor)

Vector:  [1 2 3]

Matrix:  [[1 2 3]
 [4 5 6]]

Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim) # n dimensions
print("Size ", arr.size)
print("DType ", arr.dtype) # data type

Shape  (2, 3)
Dimension  2
Size  6
DType  int64
Itemsize  8


# Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

# Converts our array into 3 by 4 matrix
reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

# Flattens the array into 1D matrix
flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
