# Numpy Array operations


In [1]:
import numpy as np

In [ ]:
# Indexing and slicing in numpy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2]) # With step size
print("Negative indexing", arr[-3]) # Negative indexing -3 means last 3rd element

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [ ]:
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("Specific element", arr_2d[1, 2]) # 1st row 2nd column based on 0 index
print("Entire row: ", arr_2d[1]) # print entire row 1
print("Entire column: ", arr_2d[:, 1]) # print entire column 1

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


# Sorting

In [ ]:
# Basic sorting
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

# Sorting 2D array
# We can do row wise and column wise sorting using axis parameter 
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0)) # axis can be 0 or 1
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1)) # axis can be 0 or 1
# 0 means it sorts from top to bottom i.e column wise
# 1 means it sorts from left to right i.e row wise

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


# Filter

In [ ]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0] # Get even numbers from the array using boolean indexing
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


# Filter with mask

In [ ]:
# Masking is a technique in NumPy where you use a Boolean condition to filter elements from an array
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])
# We can also use multiple conditions

Numbers greater than 5  [ 6  7  8  9 10]


# Fancy indexing vs np.where()

In [15]:
indices = [0, 2, 4] # list of indices
print(numbers[indices])

# np.where(condition, value_if_true, value_if_false) is a vectorized conditional selection function.
# 🔹 If only a condition is given → Returns indices where the condition is True.
# 🔹 If a condition + two values is given → Returns an array with selected values (like an if-else).
where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

print("\n")
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


# Adding and removing data

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


# array compatibilty

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [19]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

#  np.vstack() stands for "Vertical Stack".
# 🔹 It stacks multiple arrays vertically (row-wise), creating a taller array.
# 🔹 The arrays must have the same number of columns to stack properly.
with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

#  np.hstack() stands for "Horizontal Stack".
# 🔹 It stacks multiple arrays horizontally (column-wise), creating a wider array.
# 🔹 The arrays must have the same number of rows to stack properly.
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [ ]:
# delete() function is used to delete elements from an array
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
